In [1]:
## sigmoid function with math.exp

In [2]:
import math

In [3]:
def basic_sigmoid(x):
    """
    compute sigmoid of x.

    :param
    x -- A scalar

    :return
    s -- sigmoid(x)
    """

    s = 1/(1+math.exp(-x))
    return s

In [4]:
basic_sigmoid(3)


0.9525741268224334

In [5]:
#sigmoid function with np.exp
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))
print(x+3)


[ 2.71828183  7.3890561  20.08553692]
[4 5 6]


In [6]:
import numpy as np

def sigmoid(x):
    """
    compute the sigmoid of x

    :param x:
    x -- A scalar or numpy array of any size

    :return:
    s -- sigmoid(x)
    """

    s = 1/(1 + np.exp(-x))

    return s


In [7]:
x = np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [8]:
#compute sigmoid derivative
def sigmoid_derivative(x):

    """
    compute the gradient (also called the slope or derivative) of the sigmoid function
    with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.

    :param x:
    x -- A scalar or numpy array

    :return:
    ds -- Your computed gradient.
    """

    s = sigmoid(x)
    ds = s * (1-s)

    return ds

In [9]:
x = np.array([1,2,3])
print("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


In [10]:
def image2vector(image):
    """
    :param image:
    image -- a numpy array of shape (length, height, depth)

    :return:
    v -- a vector of shape (length*height*depth , 1)
    """

    v = image.reshape(image.shape[0]*image.shape[1]*image[2],1)

    return v

In [17]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x
    (to have unit lenght).

    :param x:
    x -- A numpy matrix of shape (n,m)

    :return:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """

    x_norm = np.linalg.norm(x,axis = 1,keepdims=True)
    x = x/x_norm

    return x

In [18]:
x = np.array([
    [0,3,4],
    [1,6,4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]
