In [1]:
## sigmoid function with math.exp

In [2]:
import math

In [3]:
def basic_sigmoid(x):
    """
    compute sigmoid of x.

    :param
    x -- A scalar

    :return
    s -- sigmoid(x)
    """

    s = 1/(1+math.exp(-x))
    return s

In [4]:
basic_sigmoid(3)


0.9525741268224334

In [7]:
#sigmoid function with np.exp
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))
print(x+3)


[ 2.71828183  7.3890561  20.08553692]
[4 5 6]


In [10]:
import numpy as np

def sigmoid(x):
    """
    compute the sigmoid of x

    :param x:
    x -- A scalar or numpy array of any size

    :return:
    s -- sigmoid(x)
    """

    s = 1/(1 + np.exp(-x))

    return s


In [11]:
x = np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])