In [78]:
## sigmoid function with math.exp

In [79]:
import math

In [80]:
def basic_sigmoid(x):
    """
    compute sigmoid of x.

    :param
    x -- A scalar

    :return
    s -- sigmoid(x)
    """

    s = 1/(1+math.exp(-x))
    return s

In [81]:
basic_sigmoid(3)


0.9525741268224334

In [82]:
#sigmoid function with np.exp
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))
print(x+3)


[ 2.71828183  7.3890561  20.08553692]
[4 5 6]


In [83]:
import numpy as np

def sigmoid(x):
    """
    compute the sigmoid of x

    :param x:
    x -- A scalar or numpy array of any size

    :return:
    s -- sigmoid(x)
    """

    s = 1/(1 + np.exp(-x))

    return s


In [84]:
x = np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [85]:
#compute sigmoid derivative
def sigmoid_derivative(x):

    """
    compute the gradient (also called the slope or derivative) of the sigmoid function
    with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.

    :param x:
    x -- A scalar or numpy array

    :return:
    ds -- Your computed gradient.
    """

    s = sigmoid(x)
    ds = s * (1-s)

    return ds

In [86]:
x = np.array([1,2,3])
print("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


In [87]:
def image2vector(image):
    """
    :param image:
    image -- a numpy array of shape (length, height, depth)

    :return:
    v -- a vector of shape (length*height*depth , 1)
    """

    v = image.reshape(image.shape[0]*image.shape[1]*image[2],1)

    return v

In [88]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x
    (to have unit lenght).

    :param x:
    x -- A numpy matrix of shape (n,m)

    :return:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """

    x_norm = np.linalg.norm(x,axis = 1,keepdims=True)
    x = x/x_norm

    return x

In [89]:
x = np.array([
    [0,3,4],
    [1,6,4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [90]:
#softmax function definition
def softmax(x):

    """
    Calculates the softmax for each row of the input x.

    :param x:
    x -- A numpy matrix of shape (m,n)

    :return:
    s -- A numpy matrix equal to the softmax of x, of shape (m,n)
    """

    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis=1, keepdims=True)
    s = x_exp/x_sum
    return s

In [91]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]])
print('softmax(x) =' + str(softmax(x)))

softmax(x) =[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [92]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### Classic dot product of vectors implementation ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print("dot =" + str(dot) + "\n --------- Computation time =" + str(1000*(toc - tic)) + "ms")

### Classic outer prodoct implementation ###
tic = time.process_time()
outer = np.zeros((len(x1), len(x2))) # we created a Len(x1)*Len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]
toc = time.process_time()
print("outer =" + str(outer) + "\n -------- Computation time =" + str(1000*(toc - tic)) + "ms")

### Classic elementwise implementation ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i] + x2[i]
toc = time.process_time()
print("Elementwise multiplication =" + str(mul) + "\n ------- Computation time = " + str(1000*(toc - tic)) + "ms")


### Classic general dot prodoct implementation ###
W = np.random.rand(3,len(x1)) #Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for i in range(len(x1)):
        gdot[i] += W[i,j] * x1[i]
toc = time.process_time()
print("gdot = " + str(gdot) + "\n ------- Computation time = " + str(1000*(toc - tic)) + "ms")





dot =278
 --------- Computation time =0.0ms
outer =[[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
 --

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
'''
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
'''

In [ ]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### Vectorized dot prodoct of vectors ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print("dot = " + str(dot) + "\n ------ Computation time = " + str(1000*(toc - tic)) + "ms" )

### Vectorized outer prodoct ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print("outer = " + str(outer) + "\n --------- Computation time = " + str(1000*(toc - tic)) + "ms")

### Vectorized elementwise multiplication ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print("elementwise multiplication = " + str(mul) + "\n --------- Computation time = " + str(1000*(toc - tic)) + "ms")

### Vectorized general dot prodoct ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print("gdot = " + str(dot) + "\n -------- Computation time = " + str(1000*(toc - tic)) + "ms")


In [ ]:
#Graded function: L1
def L1(yhat, y):
    """
    Arguments:

    :param yhat: vector of size m (predicted labels)
    :param y: vector of size m (true labels)
    :return loss: the value of the L1 loss function defined above
    """

    loss = sum(abs(yhat - y))
    return loss

In [ ]:
yhat = np.array([0.9, .2, .1, .4, .9])
y = np.array([1,0,0,1,1])
print("L1 =" + str(L1(yhat,y)))

In [ ]:
#implimentation of l2 loss function

def L2(yhat, y):
    """
    Arguments:

    :param yhat: vector of size m (predicted labels)
    :param y: vector of size m (true labels)

    :return loss: the value of the L2 loss function defined above
    """
    x = yhat - y
    loss = np.dot(x,x)

    return loss

In [ ]:
yhat = np.array([.9 ,0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat, y)))

In [ ]:
'''
import numpy as np
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage
from lr_utils import load_dataset

%matplotlib inline
'''

In [94]:
b = True
print(b)
print(type(b))
b = 1.1
b, type(b)

True
<class 'bool'>


(1.1, float)

In [97]:
i = 2.1
i,type(i)
i = 2
i, type(i)

(2, int)

In [98]:
c = 1 +3j
c, type(c)

((1+3j), complex)

In [101]:
s = 'mammad "folanja"'
s, type(s)
print(s)

mammad "folanja"
